# Generated by Django 3.0 on 2020-10-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='catalog',
            new_name='product',
        ),
    ]
